name: Trigger auto deployment for testingacr

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/testingacr-AutoDeployTrigger-8a56c4b0-34d7-41fa-872d-8276f36c32cc.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTINGACR_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: apbcr.azurecr.io
          registryUsername: ${{ secrets.TESTINGACR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTINGACR_REGISTRY_PASSWORD }}
          containerAppName: testingacr
          resourceGroup: DEV-CONTAINER
          imageToBuild: apbcr.azurecr.io/testingacr:${{ github.sha }}
          

     

